apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: {{ .Values.service.name }}
        image: {{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
          - containerPort: {{ .Values.service.service.http }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.service.http }}
          initialDelaySeconds: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.service.http }}
          initialDelaySeconds: 15
          periodSeconds: 20


