replicaCount: 1

service:
  name: admin-dashboard
  image:
    repository: 261990183663.dkr.ecr.eu-west-1.amazonaws.com/igate-mgmt-cleantime-admin-dashboard
    tag: dev
  service:
    http: 3000
    path: /

  configMap:
    name: cleantime-admin-dashboard

resources:
  limits:
    cpu: 1500m
    memory: 1500Mi
  requests:
    cpu: 1000m
    memory: 1000Mi

namespace: backend-develop
ingress:
  name: ingress-admin-dashboard
  host: dashboard-dev.cleantime-co.com
  acm_arn: arn:aws:acm:eu-west-1:261990183663:certificate/b1e39676-9b5f-4c1c-93aa-1f108cf5037b
nodeSelector: [ ]

tolerations: [ ]

affinity: { }

