name: Deploy services via helm chart to k8s

on:
  push:
    branches: [ "dev", "staging" ]

env:
  CLUSTER_NAME: igate-dev-eks
  SERVICES_NAMESPACE_DEV: backend-develop
  SERVICES_NAMESPACE_STAGE: backend-staging
  IMAGE_TAG : ${{ github.sha }}
  ECR_REPOSITORY: igate-mgmt-cleantime-admin-dashboard


jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy services via helm chart in Development k8s AWS Account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --build-arg NPM_MODE=dev -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Update kube config
        run: aws eks update-kubeconfig --name $CLUSTER_NAME

      - name: Deploy service by helm chart to EKS
        run:
          helm upgrade admin-dashboard  ./helm/ --install   -f ./helm/values-dev.yaml   -n $SERVICES_NAMESPACE_DEV  --set service.image.tag=$IMAGE_TAG

  deploy-stage:
    if: github.ref == 'refs/heads/staging'
    name: Deploy services via helm chart in staging k8s AWS Account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --build-arg NPM_MODE=staging -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Update kube config
        run: aws eks update-kubeconfig --name $CLUSTER_NAME

      - name: Deploy service by helm chart to EKS
        run:
          helm upgrade admin-dashboard  ./helm/ --install   -f ./helm/values-stage.yaml   -n $SERVICES_NAMESPACE_STAGE  --set service.image.tag=$IMAGE_TAG

